data = [
    {
        id: 1,
        type: 'UI/UX design',
        title: 'Dribble',
        desc: 'Discover professional layouts and beautiful designs of full web-pages and components.',
        url: 'https://dribbble.com/',
        img: 'dribble.png',
    },
    {
        id: 2,
        type: 'UI/UX design',
        title: 'UI Design Daily',
        desc: 'Many predesigned elements to inspire from.',
        url: 'https://www.uidesigndaily.com/',
        img: 'ui-design-daily.png',
    },
    {
        id: 3,
        type: 'UI/UX design',
        title: 'Trianglify',
        desc: 'Generate beautiful svg backgrounds made of triangles and gradients.',
        url: 'https://trianglify.io/',
        img: 'trianglify.png',
    },
    {
        id: 4,
        type: 'UI/UX design',
        title: 'Remix-icon',
        desc: 'Remix Icon is a set of open source neutral style system symbols elaborately crafted for designers and developers.',
        url: 'https://remixicon.com',
        img: 'remix-icon.png',
    },
    {
        id: 5,
        type: 'ReactJS',
        title: 'React by example',
        desc: 'Code-oriented React tutorial for programmers',
        url: 'https://reactbyexample.github.io/',
        img: 'react-by-example.png',
    },
    {
        id: 6,
        type: 'ReactJS',
        title: 'DevProjects by codementor',
        desc: 'Learn programming with curated React projects',
        url: 'https://www.codementor.io/projects/reactjs',
        img: 'codementor.png',
    },
    {
        id: 7,
        type: 'JavaScript',
        title: 'Javascript design patterns',
        desc: 'Object oriented programming javascript guide with design patterns for humans',
        url: 'https://github.com/sohamkamani/javascript-design-patterns-for-humans',
        img: 'js-design-patterns-oop.png',
    },
    {
        id: 8,
        type: 'APIs',
        title: 'RapidAPI',
        desc: 'Set of many useful APIs, many of them free to use, for a limited extent.',
        url: 'https://rapidapi.com/hub',
        img: 'rapidapi.png',
    },
    {
        id: 9,
        type: 'UI/UX design',
        title: 'Squarespace',
        desc: 'Squarespace offers many different website templates grouped by categories.',
        url: 'https://www.squarespace.com/templates',
        img: 'squarespace.png',
    },
    {
        id: 10,
        type: 'APIs',
        title: 'Coingecko',
        desc: 'Free cryptocurrency API with many different queries available. No API key needed.',
        url: 'https://www.coingecko.com/pl/api',
        img: 'coingecko.png',
    },
    {
        id: 11,
        type: 'JavaScript',
        title: 'Advent of Code',
        desc: 'Twenty five enteratining coding riddles to solve in 25 days of December while waiting for Christmas Eve.',
        url: 'https://adventofcode.com/',
        img: 'advent-of-code.png',
    },
    {
        id: 12,
        type: 'Reddit',
        title: 'r/webdev',
        desc: 'A community dedicated to all things web development: both front-end and back-end.',
        url: 'https://www.reddit.com/r/webdev/',
        img: 'r-webdev.jpg',
    },
    {
        id: 13,
        type: 'Reddit',
        title: 'r/web_design',
        desc: 'A community dedicated to all things web design.',
        url: 'https://www.reddit.com/r/web_design/',
        img: 'r-web_design.png',
    },
    {
        id: 14,
        type: 'Reddit',
        title: 'r/learnjavascript',
        desc: 'This subreddit is for anyone who wants to learn JavaScript or help others do so. ',
        url: 'https://www.reddit.com/r/learnjavascript',
        img: 'r-learnjavascript.png',
    },
    {
        id: 15,
        type: 'JavaScript',
        title: 'Github repos to become better JS developer',
        desc: 'Yeah, JavaScript is cool right. Here some GitHub Repos that help you to become better JavaScript developer.',
        url: 'https://devdojo.com/arpit/github-repos-to-become-better-javascript-developer',
        img: 'github-repos-to-become-better-js-dev.png',
    },
    {
        id: 16,
        type: 'JavaScript',
        title: 'Eloquent JavaScript',
        desc: 'This is a book about JavaScript, programming, and the wonders of the digital.',
        url: 'https://eloquentjavascript.net/',
        img: 'eloquent-javascript.png',
    },
]
